import image from "../assets/image.png";

const scheduleDetails = [
  {
    date: "27th Feb",
    events: [
      {
        id: 1,
        eventName: "Track Introduction",
        description: "Introduction to the tracks and themes of the hackathon.",
        image: image,
        time: "9:00 AM",
        whatsapp: "",
        loc: "",
      },
      {
        id: 2,
        eventName: "Round 0: Ideation",
        description: "Teams brainstorm and come up with innovative ideas.",
        image: image,
        time: "10:00 AM",
        whatsapp: "",
        loc: "",
      },
      {
        id: 3,
        eventName: "Round 0 Result",
        description: "Results of the ideation round are announced.",
        image: image,
        time: "1:00 PM",
        whatsapp: "",
        loc: "",
      },
      {
        id: 4,
        eventName: "Hack Begins",
        description: "The hacking phase officially starts.",
        image: image,
        time: "2:00 PM",
        whatsapp: "",
        loc: "",
      },
    ],
  },
  {
    date: "28th Feb",
    events: [
      {
        id: 5,
        eventName: "Round 1 Review",
        description: "First round of project reviews by the panel(No elimination).",
        image: image,
        time: "12:30 AM",
        whatsapp: "",
        loc: "",
      },
      {
        id: 6,
        eventName: "Round 2 Review",
        description: "Second round of project reviews by the panel.",
        image: image,
        time: "4:00 PM",
        whatsapp: "",
        loc: "",
      },
      {
        id: 7,
        eventName: "Round 2 Results",
        description: "Results of the second round are announced.",
        image: image,
        time: "7:30 PM",
        whatsapp: "",
        loc: "",
      },
    ],
  },
  {
    date: "1st March",
    events: [
      {
        id: 8,
        eventName: "Round 3 Review",
        description: "Final round of project reviews by judges.",
        image: image,
        time: "11:00 AM",
        whatsapp: "",
        loc: "",
      },
      {
        id: 9,
        eventName: "Round 3 Results",
        description: "Results of the final round are announced.",
        image: image,
        time: "2:00 PM",
        whatsapp: "",
        loc: "",
      },
      {
        id: 10,
        eventName: "Final Pitches",
        description: "Teams present their final pitches to the judges.",
        image: image,
        time: "3:00 PM",
        whatsapp: "",
        loc: "",
      },
      {
        id: 11,
        eventName: "Closing Ceremony",
        description: "Closing ceremony and announcement of winners.",
        image: image,
        time: "5:00 PM",
        whatsapp: "",
        loc: "",
      },
    ],
  },
];

export default scheduleDetails;